name: hola-mundo 
on: [push] 
jobs:
  hola-mundo: 
    runs-on: ubuntu-latest 
    steps: 
      - name: CheckoutV3  
        uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 

      - name: Correr Script 
        run: bash hola-mundo.sh 
